name: widget-server-pipeline-dockerhub

on:
  push:
    branches:
      - "main"

jobs:
  build:
    name: build docker image
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        id: checkout
        uses: actions/checkout@v4

      - name: login to dockerhub
        id: login-dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{vars.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}

      - name: generate image tag
        id: generate-tag
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: build and push image to dockerhub
        id: build-and-push-image
        env:
          DOCKERHUB_REPOSITORY: ${{vars.DOCKERHUB_REPOSITORY}}
          IMAGE_TAG: ${{steps.generate-tag.outputs.sha}}
        run: |
          docker build -t $DOCKERHUB_REPOSITORY:$IMAGE_TAG .
          docker push $DOCKERHUB_REPOSITORY:$IMAGE_TAG
